In [30]:
import pandas as pd
import datetime
from datetime import datetime as dt
import os

In [101]:
# Read Data
data_path = "user01-06/user06"
dir_list = os.listdir(data_path)

user_all_data = []

for item in dir_list:
    csv_file = data_path + "/" + item + "/" + item + "_label.csv"
    rdr = pd.read_csv(csv_file)
    user_all_data.append(rdr)

df_all = pd.concat(user_all_data, axis=0)
df_all['ts']=pd.to_datetime(df_all['ts'], unit='s')
df_all

,ts,action,actionOption,actionSub,actionSubOption,condition,conditionSub1Option,conditionSub2Option,place,emotionPositive,emotionTension,activity
0,2020-09-19 15:29:00,recreation_media,725,NaN,NaN,WITH_MANY,1.0,2.0,home,5,2,3
1,2020-09-19 15:30:00,recreation_media,725,NaN,NaN,WITH_MANY,1.0,2.0,home,5,2,3
2,2020-09-19 15:31:00,recreation_media,725,NaN,NaN,WITH_MANY,1.0,2.0,home,5,2,3
3,2020-09-19 15:32:00,recreation_media,725,NaN,NaN,WITH_MANY,1.0,2.0,home,5,2,3
4,2020-09-19 15:33:00,recreation_media,725,NaN,NaN,WITH_MANY,1.0,2.0,home,5,2,3
...,...,...,...,...,...,...,...,...,...,...,...,...
820,2020-09-16 14:01:00,recreation_media,722,NaN,NaN,ALONE,NaN,NaN,home,6,1,3
821,2020-09-16 14:02:00,recreation_media,722,NaN,NaN,ALONE,NaN,NaN,home,6,1,3
822,2020-09-16 14:03:00,recreation_media,722,NaN,NaN,ALONE,NaN,NaN,home,6,1,3
823,2020-09-16 14:04:00,recreation_media,722,NaN,NaN,ALONE,NaN,NaN,home,6,1,3
824,2020-09-16 14:05:00,recreation_media,722,NaN,NaN,ALONE,NaN,NaN,home,6,1,3

In [106]:
type_actions = list(df_all['action'].drop_duplicates())
action_count = df_all['action'].value_counts()
type_actionOptions = list(df_all['actionOption'].drop_duplicates())
actionOption_count = df_all['actionOption'].value_counts()
actionOption_dict = {'111': 'Sleep', '112': 'Sleepless', '121': 'Meal', '122': 'Snack', '131': 'Medical services, treatments, sick rest', '132': 'Personal hygiene (bath)', '133': 'Appearance management (makeup, change of clothes)', '134': 'Beauty-related services', '211': 'Main job', '212': 'Side job', '213': 'Rest during work', '22': 'Job search', '311': 'School class / seminar (listening)', '312': 'Break between classes', '313': 'School homework, self-study (individual)', '314': 'Team project (in groups)', '321': 'Private tutoring (offline)', '322': 'Online courses', '41': 'Preparing food and washing dishes', '42': 'Laundry and ironing', '43': 'Housing management and cleaning', '44': 'Vehicle management', '45': 'Pet and plant caring', '46': 'Purchasing goods and services (grocery/take-out)', '51': 'Caring for children under 10 who live together', '52': 'Caring for elementary, middle, and high school students over 10 who live together', '53': 'Caring for a spouse', '54': 'Caring for parents and grandparents who live together', '55': 'Caring for other family members who live together', '56': 'Caring for parents and grandparents who do not live together', '57': 'Caring for other family members who do not live together', '81': 'Personal care-related travel', '82': 'Commuting and work-related travel', '83': 'Education-related travel', '84': 'Travel related to housing management', '85': 'Travel related to caring for family and household members', '86': 'Travel related to participation and volunteering', '87': 'Socializing and leisure-related travel', '61': 'Religious activities', '62': 'Political activity', '63': 'Ceremonial activities', '64': 'Volunteer', '711': 'Offline communication', '712': 'Video or voice call', '713': 'Text or email (Online)', '721': 'Reading books, newspapers, and magazines', '722': 'Watching TV or video', '723': 'Listening to audio', '724': 'Internet search or blogging', '725': 'Gaming (mobile, computer, video)', '741': 'Watching a sporting event', '742': 'Watching movie', '743': 'Concerts and plays', '744': 'Amusement Park, zoo', '745': 'Festival, carnival', '746': 'Driving, sightseeing, excursion', '751': 'Walking', '752': 'Running, jogging', '753': 'Climbing, hiking', '754': 'Biking', '755': 'Ball games (soccer, basketball, baseball, tennis, etc)', '756': 'Camping, fishing', '761': 'Group games (board games, card games, puzzles, etc.)', '762': 'Personal hobbies (woodworking, gardening, etc.)', '763': 'Group performances (orchestra, choir, troupe, etc.)', '764': 'Liberal arts and learning (languages, musical instruments, etc.)', '791': 'Nightlife', '792': 'Smoking', '793': 'Do nothing and rest', '91': 'Online shopping', '92': 'Offline shopping'}
type_conditions = list(df_all['condition'].drop_duplicates())
condition_count = df_all['condition'].value_counts()
type_activity = list(df_all['activity'].drop_duplicates())
type_activity

[3, 4, 0, 2, 6, 1]

In [103]:
for action in type_actions:
  print("{}: {:.3f}%".format(action, 100*action_count[action]/sum(list(action_count))))
  for actionOption in list(df_all['actionOption'][df_all['action']==action].drop_duplicates()):
    print("       ã„´{}: {:.3f}%".format(actionOption_dict[str(actionOption)], 100*actionOption_count[actionOption]/sum(list(action_count))))

recreation_media: 42.850%
       ã„´Gaming (mobile, computer, video): 21.201%
       ã„´Internet search or blogging: 8.184%
       ã„´Watching TV or video: 11.956%
       ã„´Reading books, newspapers, and magazines: 1.509%
socialising: 4.285%
       ã„´Offline communication: 3.514%
       ã„´Text or email (Online): 0.299%
       ã„´Video or voice call: 0.472%
meal: 4.809%
       ã„´Meal: 4.485%
       ã„´Snack: 0.324%
personal_care: 3.756%
       ã„´Appearance management (makeup, change of clothes): 2.333%
       ã„´Personal hygiene (bath): 1.423%
travel: 8.007%
       ã„´Commuting and work-related travel: 5.031%
       ã„´Travel related to participation and volunteering: 1.115%
       ã„´Travel related to housing management: 0.873%
       ã„´Personal care-related travel: 0.066%
       ã„´Socializing and leisure-related travel: 0.923%
work: 26.745%
       ã„´Side job: 4.059%
       ã„´Main job: 18.807%
       ã„´Rest during work: 3.879%
household: 0.976%
       ã„´Housing management and cleaning: 0.529%
       ã„´Laundry and ironing: 0.086%
       ã„´Purchasing goods and services (grocery/take-out): 0.361%
recreation_etc: 0.685%
       ã„´Do nothing and rest: 0.685%
sleep: 6.634%
       ã„´Sleep: 6.634%
community_interaction: 0.357%
       ã„´Ceremonial activities: 0.357%
shop: 0.664%
       ã„´Offline shopping: 0.504%
       ã„´Online shopping: 0.160%
outdoor_act: 0.234%
       ã„´Running, jogging: 0.234%

In [109]:
df_all[df_all['action']=='recreation_media']['emotionPositive'].value_counts()

<bound method IndexOpsMixin.value_counts of 0      5
1      5
2      5
3      5
4      5
      ..
820    6
821    6
822    6
823    6
824    6
Name: emotionPositive, Length: 10451, dtype: int64>

In [43]:
survey = pd.read_csv('user_survey_2020.csv')
survey

,userId,date,amPm,startInput,endInput,sleep,sleepProblem,dream,amCondition,amEmotion,pmEmotion,pmStress,pmFatigue,caffeine,cAmount(ml),alcohol,aAmount(ml)
0,user24,2020-08-29,am,2020-08-29 21:23,2020-08-29 21:23,4.0,0.0,3.0,3.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,user24,2020-08-29,pm,2020-08-29 21:23,2020-08-29 21:23,NaN,NaN,NaN,NaN,NaN,4.0,4.0,2.0,NaN,NaN,NaN,NaN
2,user24,2020-08-30,am,2020-08-30 7:41,2020-08-30 7:41,3.0,2.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,user24,2020-08-30,pm,2020-08-30 22:43,2020-08-30 22:43,NaN,NaN,NaN,NaN,NaN,4.0,5.0,2.0,coffee,200.0,NaN,NaN
4,user24,2020-08-31,am,2020-08-31 7:23,2020-08-31 7:24,3.0,2.0,2.0,3.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1225,user06,2020-10-06,pm,2020-10-07 0:07,2020-10-07 0:08,NaN,NaN,NaN,NaN,NaN,4.0,4.0,4.0,NaN,NaN,NaN,NaN
1226,user06,2020-10-07,am,2020-10-07 8:02,2020-10-07 8:05,2.0,9.0,4.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1227,user06,2020-10-07,pm,2020-10-08 1:57,2020-10-08 1:57,NaN,NaN,NaN,NaN,NaN,5.0,2.0,3.0,coffee,250.0,NaN,NaN
1228,user06,2020-10-08,am,2020-10-08 8:23,2020-10-08 8:24,3.0,0.0,4.0,2.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1229,user06,2020-10-08,pm,2020-10-08 23:30,2020-10-08 23:31,NaN,NaN,NaN,NaN,NaN,3.0,2.0,2.0,coffee,300.0,NaN,NaN

In [44]:
sleep = pd.read_csv('user_sleep_2020.csv')
sleep

,userId,timezone,date,startDt,endDt,lastUpdate,wakeupduration,lightsleepduration,deepsleepduration,wakeupcount,...,hr_average,hr_min,hr_max,rr_average,rr_min,rr_max,breathing_disturbances_intensity,snoring,snoringepisodecount,sleep_score
0,user24,Asia/Seoul,2020-08-30,1598708760,1598740860,1598748252,3840,13800,9000,3,...,72,63,82,15,10,20,10,840,1,86
1,user24,Asia/Seoul,2020-08-31,1598800140,1598825940,1598833333,4740,9540,6360,1,...,69,60,82,15,11,20,8,2700,3,52
2,user24,Asia/Seoul,2020-09-01,1598885940,1598908800,1598916190,1920,8760,4740,1,...,70,58,94,15,12,23,8,0,0,61
3,user24,Asia/Seoul,2020-09-02,1598979420,1598999580,1599006969,2760,7740,7440,1,...,68,60,80,15,12,19,-1,240,1,40
4,user24,Asia/Seoul,2020-09-03,1599060780,1599085980,1599093370,3900,11640,7620,1,...,71,61,83,15,11,25,7,300,1,55
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
610,user06,Asia/Seoul,2020-10-05,1601831040,1601861820,1601862001,8460,11820,4560,1,...,48,43,81,17,12,22,13,2400,5,60
611,user06,Asia/Seoul,2020-10-06,1601923560,1601951220,1601951380,1920,13200,7500,1,...,52,47,84,17,10,23,10,1380,4,79
612,user06,Asia/Seoul,2020-10-07,1602001320,1602023760,1602031150,12420,8520,1500,3,...,47,42,76,16,12,20,-1,1620,4,20
613,user06,Asia/Seoul,2020-10-08,1602091020,1602110280,1602117673,4380,9240,4560,2,...,52,47,68,17,10,20,-1,2280,2,20
614,user06,Asia/Seoul,2020-10-09,1602183900,1602220140,1602227533,3360,17820,7140,1,...,52,45,69,17,10,23,12,8340,6,87

In [94]:
x="""111	Sleep

112	Sleepless

121	Meal

122	Snack

131	Medical services, treatments, sick rest

132	Personal hygiene (bath)

133	Appearance management (makeup, change of clothes)

134	Beauty-related services

211	Main job

212	Side job

213	Rest during work

22	Job search

311	School class / seminar (listening)

312	Break between classes

313	School homework, self-study (individual)

314	Team project (in groups)

321	Private tutoring (offline)

322	Online courses

41	Preparing food and washing dishes

42	Laundry and ironing

43	Housing management and cleaning

44	Vehicle management

45	Pet and plant caring

46	Purchasing goods and services (grocery/take-out)

51	Caring for children under 10 who live together

52	Caring for elementary, middle, and high school students over 10 who live together

53	Caring for a spouse

54	Caring for parents and grandparents who live together

55	Caring for other family members who live together

56	Caring for parents and grandparents who do not live together

57	Caring for other family members who do not live together

81	Personal care-related travel

82	Commuting and work-related travel

83	Education-related travel

84	Travel related to housing management

85	Travel related to caring for family and household members

86	Travel related to participation and volunteering

87	Socializing and leisure-related travel

61	Religious activities

62	Political activity

63	Ceremonial activities

64	Volunteer

711	Offline communication

712	Video or voice call

713	Text or email (Online)

721	Reading books, newspapers, and magazines

722	Watching TV or video

723	Listening to audio

724	Internet search or blogging

725	Gaming (mobile, computer, video)

741	Watching a sporting event

742	Watching movie

743	Concerts and plays

744	Art galleries and museums

744	Amusement Park, zoo

745	Festival, carnival

746	Driving, sightseeing, excursion

751	Walking

752	Running, jogging

753	Climbing, hiking

754	Biking

755	Ball games (soccer, basketball, baseball, tennis, etc)

756	Personal exercises (yoga, pilates, etc.)

756	Camping, fishing

761	Group games (board games, card games, puzzles, etc.)

762	Personal hobbies (woodworking, gardening, etc.)

763	Group performances (orchestra, choir, troupe, etc.)

764	Liberal arts and learning (languages, musical instruments, etc.)

791	Nightlife

792	Smoking

793	Do nothing and rest

91	Online shopping

92	Offline shopping"""

In [95]:
l = x.split('\n')
d = {}
for i in l:
  if len(i)>1:
    d[i.split('\t')[0]] = i.split('\t')[1]

In [96]:
print(d)

{'111': 'Sleep', '112': 'Sleepless', '121': 'Meal', '122': 'Snack', '131': 'Medical services, treatments, sick rest', '132': 'Personal hygiene (bath)', '133': 'Appearance management (makeup, change of clothes)', '134': 'Beauty-related services', '211': 'Main job', '212': 'Side job', '213': 'Rest during work', '22': 'Job search', '311': 'School class / seminar (listening)', '312': 'Break between classes', '313': 'School homework, self-study (individual)', '314': 'Team project (in groups)', '321': 'Private tutoring (offline)', '322': 'Online courses', '41': 'Preparing food and washing dishes', '42': 'Laundry and ironing', '43': 'Housing management and cleaning', '44': 'Vehicle management', '45': 'Pet and plant caring', '46': 'Purchasing goods and services (grocery/take-out)', '51': 'Caring for children under 10 who live together', '52': 'Caring for elementary, middle, and high school students over 10 who live together', '53': 'Caring for a spouse', '54': 'Caring for parents and grandparents who live together', '55': 'Caring for other family members who live together', '56': 'Caring for parents and grandparents who do not live together', '57': 'Caring for other family members who do not live together', '81': 'Personal care-related travel', '82': 'Commuting and work-related travel', '83': 'Education-related travel', '84': 'Travel related to housing management', '85': 'Travel related to caring for family and household members', '86': 'Travel related to participation and volunteering', '87': 'Socializing and leisure-related travel', '61': 'Religious activities', '62': 'Political activity', '63': 'Ceremonial activities', '64': 'Volunteer', '711': 'Offline communication', '712': 'Video or voice call', '713': 'Text or email (Online)', '721': 'Reading books, newspapers, and magazines', '722': 'Watching TV or video', '723': 'Listening to audio', '724': 'Internet search or blogging', '725': 'Gaming (mobile, computer, video)', '741': 'Watching a sporting event', '742': 'Watching movie', '743': 'Concerts and plays', '744': 'Amusement Park, zoo', '745': 'Festival, carnival', '746': 'Driving, sightseeing, excursion', '751': 'Walking', '752': 'Running, jogging', '753': 'Climbing, hiking', '754': 'Biking', '755': 'Ball games (soccer, basketball, baseball, tennis, etc)', '756': 'Camping, fishing', '761': 'Group games (board games, card games, puzzles, etc.)', '762': 'Personal hobbies (woodworking, gardening, etc.)', '763': 'Group performances (orchestra, choir, troupe, etc.)', '764': 'Liberal arts and learning (languages, musical instruments, etc.)', '791': 'Nightlife', '792': 'Smoking', '793': 'Do nothing and rest', '91': 'Online shopping', '92': 'Offline shopping'}